# This is a basic workflow to help you get started with Actions

name: Upload to the upload server

# Controls when the workflow will run
on:
  push:
    branches: [develop, master]
    tags:
      - rocm-5.1.0

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: getting branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch_name
      - name: zipping files
        run: zip -r ${{ github.event.repository.name }}_${{ steps.branch_name.outputs.branch }}_rocm-5.1.0.zip . -x '*.git*' '*.idea*'
      - name: echo-step
        run: echo "${{ steps.branch_name.outputs.branch }}"
      - name: uploading archive to prod
        if: ${{ steps.branch_name.outputs.branch == 'master' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ${{ github.event.repository.name }}_${{ steps.branch_name.outputs.branch }}_rocm-5.1.0.zip
          remote_path: '${{ secrets.PROD_UPLOAD_URL }}'
          args: '-o ConnectTimeout=5'
      - name: uploading archive to staging
        if: ${{ steps.branch_name.outputs.branch == 'develop' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ${{ github.event.repository.name }}_${{ steps.branch_name.outputs.branch }}_rocm-5.1.0.zip
          remote_path: '${{ secrets.STG_UPLOAD_URL }}'
          args: '-o ConnectTimeout=5'
